wandb_version: 1

c:
  desc: null
  value: configs/config.yaml
project_name:
  desc: null
  value: FGVC-HERBS
notes:
  desc: null
  value: no inverse
exp_name:
  desc: null
  value: basline
use_wandb:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: bosyuan
train_root:
  desc: null
  value: ./CUB200-2011/train/
val_root:
  desc: null
  value: ./CUB200-2011/validate/
data_size:
  desc: null
  value: 384
num_workers:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 8
model_name:
  desc: null
  value: swin-t
pretrained:
  desc: null
  value: null
optimizer:
  desc: null
  value: SGD
max_lr:
  desc: null
  value: 0.0005
wdecay:
  desc: null
  value: 0.0003
max_epochs:
  desc: null
  value: 80
warmup_batchs:
  desc: null
  value: 1500
use_amp:
  desc: null
  value: true
use_fpn:
  desc: null
  value: true
fpn_size:
  desc: null
  value: 1536
use_selection:
  desc: null
  value: true
num_classes:
  desc: null
  value: 200
num_selects:
  desc: null
  value:
    layer1: 256
    layer2: 128
    layer3: 64
    layer4: 32
use_combiner:
  desc: null
  value: true
lambda_b0:
  desc: null
  value: 1.375
lambda_b:
  desc: null
  value: 0.3
lambda_s:
  desc: null
  value: 0.0
lambda_n:
  desc: null
  value: 5.0
lambda_c:
  desc: null
  value: 1.0
update_freq:
  desc: null
  value: 4
log_freq:
  desc: null
  value: 100
eval_freq:
  desc: null
  value: 10
temperature:
  desc: null
  value: 64
save_dir:
  desc: null
  value: ./records/FGVC-HERBS/basline/
device:
  desc: null
  value: cuda:0
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703586419.767866
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.8.0
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
